output "cloud_run_service_url" {
  description = "The URL of the deployed Cloud Run service"
  value       = google_cloud_run_v2_service.app_service.uri
}

output "bq_connection_service_account" {
  description = "Service account generated by the BigQuery connection"
  value       = google_bigquery_connection.remote_connection.cloud_resource[0].service_account_id
}

output "dlp_inspect_template_name" {
  description = "The DLP Inspect template name"
  value       = google_data_loss_prevention_inspect_template.nyl_inspect_template.name
}

output "dlp_deidentify_template_name" {
  description = "The DLP De-identify template name"
  value       = google_data_loss_prevention_deidentify_template.nyl_deidentify_template.name
}
