output "routine_id" {
  description = "The BigQuery routine ID."
  value       = google_bigquery_routine.remote_function.routine_id
}

output "routine_name" {
  description = "The fully qualified resource name of the BigQuery routine."
  value       = google_bigquery_routine.remote_function.id
}

output "connection_id" {
  description = "The BigQuery Cloud Resource connection ID."
  value       = local.effective_connection_id
}

output "connection_service_account" {
  description = "The service account email generated by the BigQuery connection."
  value       = local.connection_sa_email
}
